eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: peliculas
          uri: lb://msvc-peliculas
          predicates:
            - Path=/api/peliculas/**
        - id: cartelera
          uri: lb://msvc-cartelera
          predicates:
            - Path=/api/cartelera/**
        - id: sedes
          uri: lb://msvc-sedes
          predicates:
            - Path=/api/sedes/**
        - id: confiteria
          uri: lb://msvc-confiteria
          predicates:
            - Path=/api/confiteria/**
        - id: ventas
          uri: lb://msvc-ventas
          predicates:
            - Path=/api/ventas/**
