server:
  port: 8090

spring:
  application:
    name: msvc-peliculas
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=BDMovieCity;trustServerCertificate=true
    username: cesar
    password: 123

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka